In [2]:
import pandas as pd
import glob

In [6]:

# Get a list of all Excel files in the folder
excel_files = glob.glob('C:\\Users\\advan\\OneDrive\\Desktop\\Infinite Uptime\\DATA\\Alerts\\May\\*.xlsx')  # Replace 'path_to_folder' with the actual folder path

# List to store DataFrames for each file
dataframes = []

# Read each Excel file into a DataFrame and store in the list
for file in excel_files:
    df = pd.read_excel(file)
    dataframes.append(df)

# Concatenate all DataFrames into a single DataFrame
merged_df = pd.concat(dataframes, ignore_index=True)

# Save the merged DataFrame to a new Excel file
merged_df.to_excel('C:\\Users\\advan\\OneDrive\\Desktop\\Infinite Uptime\\DATA\\May.xlsx', index=False)

C:\Users\advan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
C:\Users\advan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
C:\Users\advan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)
C:\Users\advan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

Cleaning the Data

In [15]:
may = pd.read_excel('C:\\Users\\advan\\OneDrive\\Desktop\\Infinite Uptime\\DATA\\May.xlsx')
new_may=may.drop(['machine_name','monitor_name','timestamp','CoE Remarks if any','DRS ID (Existing / Newly created)'],axis=1)
new_may

,plant_name,plant_id,machine_id,parameter,magnitude,CoE Validation as per SOP,Customer Validation,Increase in magnitude (multiplier),monitor_id,units,org_name
0,"JSW Steel Coated Products Ltd, Kalmeshwar",1584,8056,TOTAL ACCELERATION,123.60,True,NaN,139.35,64045,(m/s^2)^2,JSW Steel Ltd
1,JSW_ACCIL_Bawal,1823,8682,TEMPERATURE,70.99,True,NaN,70.99,70384,degree C,JSW Steel Ltd
2,"Kansai Nerolac Paints Limited, Bawal",1739,7130,VELOCITY,9.05,True,TP,4.76,53308,mm/s,Kansai Nerolac Paints
3,Toppan Speciality Films Pvt Ltd_Ropar,95,4190,VELOCITY,3.44,False,NaN,6.37,305,mm/s,TOPPAN SPECIALITY FILMS PVT LTD
4,JSW VJNR WRM-2,1726,6782,VELOCITY,3.15,False,NaN,4.90,50375,mm/s,JSW Steel Ltd
...,...,...,...,...,...,...,...,...,...,...,...
1188,UTCL_Pali,1873,9826,TEMPERATURE,65.05,NaN,NaN,65.05,79415,degree C,Ultratech Cement Ltd
1189,UTCL_Neem ka Thana,1215,3770,TEMPERATURE,65.12,NaN,NaN,65.12,57170,degree C,Ultratech Cement Ltd
1190,JSW VJNR RMHS - PCI Silo,1666,6231,VELOCITY,1.53,False,NaN,3.68,44595,mm/s,JSW Steel Ltd
1191,Radha TMT_Smelter_Chegunta_Hyd,1764,7602,TOTAL ACCELERATION,1597.73,True,NaN,3.97,59520,(m/s^2)^2,Radha Smelters Private Limited
1192,Radha TMT_Smelter_Chegunta_Hyd,1764,7602,TOTAL ACCELERATION,2511.90,True,NaN,6.65,59521,(m/s^2)^2,Radha Smelters Private Limited

In [19]:
# getting config data

config = pd.read_excel('C:\\Users\\advan\\OneDrive\\Desktop\\Infinite Uptime\\DATA\\machine_config_3July2023.xlsx')
config

,Unnamed: 0,monitor_name,monitor_id,machine_name_x,machine_id,plant_name_x,CoE,org_name,mac_id,device_type,...,speed_type,brg_type,speed_range,threshold_X,threshold_Y,threshold_Z,fmax,LOR,grange,m_category
0,0,M2-CB 3 - Bearing DE - 1,119,Circulation Blower-3,63,CUMI-ABRASIVE,NaN,CUMI ABRASIVE,94:54:93:4A:1E:13,vEdge,...,FIXED,75808,{},"[9.0, 6.0, 2.3]","[9.0, 4.5, 1.5]","[9.0, 5.0, 1.5]",1300,1600,0,bearing
1,1,M2-CB 4 - Bearing DE - 1,120,Circulation Blower-4,64,CUMI-ABRASIVE,NaN,CUMI ABRASIVE,94:54:93:4A:59:65,vEdge 1.6,...,FIXED,75808,{},"[9.0, 5.0, 1.1]","[8.0, 4.0, 1.0]","[9.0, 4.5, 1.2]",1300,1600,0,bearing
2,2,M2-CB 8 - Bearing DE - 1,121,Circulation Blower-8,65,CUMI-ABRASIVE,NaN,CUMI ABRASIVE,94:54:93:4A:09:2E,vEdge,...,FIXED,75808,{},"[9.0, 6.0, 2.5]","[8.0, 4.5, 1.0]","[9.0, 6.0, 1.2]",1300,1600,0,bearing
3,3,M2-SD1-BLWR MTR-BEARING DE-1,122,Suction Drum-1,66,CUMI-ABRASIVE,NaN,CUMI ABRASIVE,94:54:93:4A:1E:79,vEdge 1.6,...,FIXED,75808,{},"[8.0, 6.0, 1.0]","[6.0, 4.0, 1.2]","[6.0, 4.0, 1.2]",1300,1600,0,blower
4,4,M2-SD2-BLWR MTR-BEARING DE-1,123,Suction Drum-2,67,CUMI-ABRASIVE,NaN,CUMI ABRASIVE,94:54:93:4A:1D:FE,vEdge,...,FIXED,75808,{},"[8.0, 6.0, 1.0]","[8.0, 4.5, 0.5]","[7.0, 4.5, 0.5]",1300,1600,0,blower
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24420,24420,HIIGH PRESSURE WATER PUMP-1- PNDE,90487,OLD-WTP HIIGH PRESSURE WATER PUMP-1-PUMP,12127,"Moon Beverages Ltd, Greater Noida",NaN,Moon Beverages Ltd,4C:75:25:ED:05:BA,vEdge 4.2,...,FIXED,0,{},"[11.2, 4.5, 0.5]","[11.2, 4.5, 0.5]","[11.2, 4.5, 0.5]",1300,0,4,pump
24421,24421,OLD WTP HIIGH PRESSURE WATER PUMP-2- PDE,90495,OLD-WTP HIIGH PRESSURE WATER PUMP-2-PUMP,12128,"Moon Beverages Ltd, Greater Noida",NaN,Moon Beverages Ltd,4C:75:25:F7:25:B2,vEdge 4.2,...,FIXED,0,{},"[11.2, 4.5, 0.5]","[11.2, 4.5, 0.5]","[11.2, 4.5, 0.5]",1300,0,4,pump
24422,24422,OLD HIIGH PRESSURE WATER PUMP-2- PNDE,90496,OLD-WTP HIIGH PRESSURE WATER PUMP-2-PUMP,12128,"Moon Beverages Ltd, Greater Noida",NaN,Moon Beverages Ltd,4C:75:25:F7:0C:1E,vEdge 4.2,...,FIXED,0,{},"[11.2, 4.5, 0.5]","[11.2, 4.5, 0.5]","[11.2, 4.5, 0.5]",1300,3200,4,pump
24423,24423,OLD WTP HIIGH PRESSURE WATER PUMP-2- MNDE,90488,OLD-WTP HIIGH PRESSURE WATER PUMP-2-MOTOR,12129,"Moon Beverages Ltd, Greater Noida",NaN,Moon Beverages Ltd,4C:75:25:F7:0F:82,vEdge 4.2,...,FIXED,0,{},"[11.2, 4.5, 0.5]","[11.2, 4.5, 0.5]","[11.2, 4.5, 0.5]",1300,0,4,pump
24424,24424,OLD WTP HIIGH PRESSURE WATER PUMP-2- MDE,90489,OLD-WTP HIIGH PRESSURE WATER PUMP-2-MOTOR,12129,"Moon Beverages Ltd, Greater Noida",NaN,Moon Beverages Ltd,4C:75:25:F7:0B:96,vEdge 4.2,...,FIXED,0,{},"[11.2, 4.5, 0.5]","[11.2, 4.5, 0.5]","[11.2, 4.5, 0.5]",1300,3200,4,pump

In [22]:
new_config = config[['monitor_id','plant_name_y','mounting_condition','speed','speed_type','m_category']]
new_config

,monitor_id,plant_name_y,mounting_condition,speed,speed_type,m_category
0,119,CUMI-ABRASIVE,NaN,1475.0,FIXED,bearing
1,120,CUMI-ABRASIVE,NaN,1475.0,FIXED,bearing
2,121,CUMI-ABRASIVE,NaN,1475.0,FIXED,bearing
3,122,CUMI-ABRASIVE,NaN,2935.0,FIXED,blower
4,123,CUMI-ABRASIVE,NaN,2935.0,FIXED,blower
...,...,...,...,...,...,...
24420,90487,"Moon Beverages Ltd, Greater Noida",At Ground,1475.0,FIXED,pump
24421,90495,"Moon Beverages Ltd, Greater Noida",At Ground,1475.0,FIXED,pump
24422,90496,"Moon Beverages Ltd, Greater Noida",At Ground,1475.0,FIXED,pump
24423,90488,"Moon Beverages Ltd, Greater Noida",At Ground,1475.0,FIXED,pump
24424,90489,"Moon Beverages Ltd, Greater Noida",At Ground,1475.0,FIXED,pump

In [23]:
new_config.rename(columns={'plant_name_y': 'plant_name'}, inplace=True)
new_config

C:\Users\advan\AppData\Local\Temp\ipykernel_24148\342739793.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_config.rename(columns={'plant_name_y': 'plant_name'}, inplace=True)

,monitor_id,plant_name,mounting_condition,speed,speed_type,m_category
0,119,CUMI-ABRASIVE,NaN,1475.0,FIXED,bearing
1,120,CUMI-ABRASIVE,NaN,1475.0,FIXED,bearing
2,121,CUMI-ABRASIVE,NaN,1475.0,FIXED,bearing
3,122,CUMI-ABRASIVE,NaN,2935.0,FIXED,blower
4,123,CUMI-ABRASIVE,NaN,2935.0,FIXED,blower
...,...,...,...,...,...,...
24420,90487,"Moon Beverages Ltd, Greater Noida",At Ground,1475.0,FIXED,pump
24421,90495,"Moon Beverages Ltd, Greater Noida",At Ground,1475.0,FIXED,pump
24422,90496,"Moon Beverages Ltd, Greater Noida",At Ground,1475.0,FIXED,pump
24423,90488,"Moon Beverages Ltd, Greater Noida",At Ground,1475.0,FIXED,pump
24424,90489,"Moon Beverages Ltd, Greater Noida",At Ground,1475.0,FIXED,pump

In [25]:
train = new_may.merge(new_config, on=['monitor_id', 'plant_name'], how='left')
train

,plant_name,plant_id,machine_id,parameter,magnitude,CoE Validation as per SOP,Customer Validation,Increase in magnitude (multiplier),monitor_id,units,org_name,mounting_condition,speed,speed_type,m_category
0,"JSW Steel Coated Products Ltd, Kalmeshwar",1584,8056,TOTAL ACCELERATION,123.60,True,NaN,139.35,64045,(m/s^2)^2,JSW Steel Ltd,On Rigid Concrete,1482.0,FIXED,blower
1,JSW_ACCIL_Bawal,1823,8682,TEMPERATURE,70.99,True,NaN,70.99,70384,degree C,JSW Steel Ltd,On Rigid Concrete,2940.0,FIXED,blower
2,"Kansai Nerolac Paints Limited, Bawal",1739,7130,VELOCITY,9.05,True,TP,4.76,53308,mm/s,Kansai Nerolac Paints,On Rigid Concrete,2950.0,FIXED,motor
3,Toppan Speciality Films Pvt Ltd_Ropar,95,4190,VELOCITY,3.44,False,NaN,6.37,305,mm/s,TOPPAN SPECIALITY FILMS PVT LTD,NaN,150.0,VARIABLE,bearing
4,JSW VJNR WRM-2,1726,6782,VELOCITY,3.15,False,NaN,4.90,50375,mm/s,JSW Steel Ltd,On Rigid Concrete,34.0,FIXED,gearbox
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1188,UTCL_Pali,1873,9826,TEMPERATURE,65.05,NaN,NaN,65.05,79415,degree C,Ultratech Cement Ltd,On Rigid Concrete,123.0,VARIABLE,unknown
1189,UTCL_Neem ka Thana,1215,3770,TEMPERATURE,65.12,NaN,NaN,65.12,57170,degree C,Ultratech Cement Ltd,NaN,1485.0,FIXED,bearing
1190,JSW VJNR RMHS - PCI Silo,1666,6231,VELOCITY,1.53,False,NaN,3.68,44595,mm/s,JSW Steel Ltd,NaN,60.0,FIXED,bearing
1191,Radha TMT_Smelter_Chegunta_Hyd,1764,7602,TOTAL ACCELERATION,1597.73,True,NaN,3.97,59520,(m/s^2)^2,Radha Smelters Private Limited,On Rigid Concrete,1490.0,FIXED,blower
1192,Radha TMT_Smelter_Chegunta_Hyd,1764,7602,TOTAL ACCELERATION,2511.90,True,NaN,6.65,59521,(m/s^2)^2,Radha Smelters Private Limited,On Rigid Concrete,1490.0,FIXED,blower

In [26]:
train['plant_id'].min()

95

In [31]:
v1_train = train.dropna(subset=['CoE Validation as per SOP'])
v1_train

,plant_name,plant_id,machine_id,parameter,magnitude,CoE Validation as per SOP,Customer Validation,Increase in magnitude (multiplier),monitor_id,units,org_name,mounting_condition,speed,speed_type,m_category
0,"JSW Steel Coated Products Ltd, Kalmeshwar",1584,8056,TOTAL ACCELERATION,123.60,True,NaN,139.35,64045,(m/s^2)^2,JSW Steel Ltd,On Rigid Concrete,1482.0,FIXED,blower
1,JSW_ACCIL_Bawal,1823,8682,TEMPERATURE,70.99,True,NaN,70.99,70384,degree C,JSW Steel Ltd,On Rigid Concrete,2940.0,FIXED,blower
2,"Kansai Nerolac Paints Limited, Bawal",1739,7130,VELOCITY,9.05,True,TP,4.76,53308,mm/s,Kansai Nerolac Paints,On Rigid Concrete,2950.0,FIXED,motor
3,Toppan Speciality Films Pvt Ltd_Ropar,95,4190,VELOCITY,3.44,False,NaN,6.37,305,mm/s,TOPPAN SPECIALITY FILMS PVT LTD,NaN,150.0,VARIABLE,bearing
4,JSW VJNR WRM-2,1726,6782,VELOCITY,3.15,False,NaN,4.90,50375,mm/s,JSW Steel Ltd,On Rigid Concrete,34.0,FIXED,gearbox
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1186,JSW Steel Coated Products Ltd_Tarapur_ETP,1848,9128,TEMPERATURE,66.90,UNKNOWN,NaN,66.90,73030,degree C,JSW Steel Ltd,On Steel Structure/ Resilient Base,2948.0,FIXED,blower
1187,JSW Steel Coated Products Ltd_Khopoli Works,1818,9032,TOTAL ACCELERATION,1774.96,True,NaN,10.52,72494,(m/s^2)^2,JSW Steel Ltd,At Ground,2925.0,FIXED,blower
1190,JSW VJNR RMHS - PCI Silo,1666,6231,VELOCITY,1.53,False,NaN,3.68,44595,mm/s,JSW Steel Ltd,NaN,60.0,FIXED,bearing
1191,Radha TMT_Smelter_Chegunta_Hyd,1764,7602,TOTAL ACCELERATION,1597.73,True,NaN,3.97,59520,(m/s^2)^2,Radha Smelters Private Limited,On Rigid Concrete,1490.0,FIXED,blower
1192,Radha TMT_Smelter_Chegunta_Hyd,1764,7602,TOTAL ACCELERATION,2511.90,True,NaN,6.65,59521,(m/s^2)^2,Radha Smelters Private Limited,On Rigid Concrete,1490.0,FIXED,blower

In [45]:
v2_train = v1_train[v1_train['CoE Validation as per SOP'] != 'UNKNOWN']
v2_train

,plant_name,plant_id,machine_id,parameter,magnitude,CoE Validation as per SOP,Customer Validation,Increase in magnitude (multiplier),monitor_id,units,org_name,mounting_condition,speed,speed_type,m_category
0,"JSW Steel Coated Products Ltd, Kalmeshwar",1584,8056,TOTAL ACCELERATION,123.60,True,NaN,139.35,64045,(m/s^2)^2,JSW Steel Ltd,On Rigid Concrete,1482.0,FIXED,blower
1,JSW_ACCIL_Bawal,1823,8682,TEMPERATURE,70.99,True,NaN,70.99,70384,degree C,JSW Steel Ltd,On Rigid Concrete,2940.0,FIXED,blower
2,"Kansai Nerolac Paints Limited, Bawal",1739,7130,VELOCITY,9.05,True,TP,4.76,53308,mm/s,Kansai Nerolac Paints,On Rigid Concrete,2950.0,FIXED,motor
3,Toppan Speciality Films Pvt Ltd_Ropar,95,4190,VELOCITY,3.44,False,NaN,6.37,305,mm/s,TOPPAN SPECIALITY FILMS PVT LTD,NaN,150.0,VARIABLE,bearing
4,JSW VJNR WRM-2,1726,6782,VELOCITY,3.15,False,NaN,4.90,50375,mm/s,JSW Steel Ltd,On Rigid Concrete,34.0,FIXED,gearbox
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1184,JSW VJNR Coke Oven - 3,1817,8534,VELOCITY,10.30,True,NaN,3.16,69648,mm/s,JSW Steel Ltd,At Ground,2985.0,FIXED,motor
1187,JSW Steel Coated Products Ltd_Khopoli Works,1818,9032,TOTAL ACCELERATION,1774.96,True,NaN,10.52,72494,(m/s^2)^2,JSW Steel Ltd,At Ground,2925.0,FIXED,blower
1190,JSW VJNR RMHS - PCI Silo,1666,6231,VELOCITY,1.53,False,NaN,3.68,44595,mm/s,JSW Steel Ltd,NaN,60.0,FIXED,bearing
1191,Radha TMT_Smelter_Chegunta_Hyd,1764,7602,TOTAL ACCELERATION,1597.73,True,NaN,3.97,59520,(m/s^2)^2,Radha Smelters Private Limited,On Rigid Concrete,1490.0,FIXED,blower
1192,Radha TMT_Smelter_Chegunta_Hyd,1764,7602,TOTAL ACCELERATION,2511.90,True,NaN,6.65,59521,(m/s^2)^2,Radha Smelters Private Limited,On Rigid Concrete,1490.0,FIXED,blower

In [46]:
# modifying customer feedback for training purpose
import numpy as np
v2_train['Customer Validation'] = v2_train['Customer Validation'].apply(lambda x: 0 if x == 'FP' else 1)
v2_train['CoE Validation as per SOP'] = v2_train['CoE Validation as per SOP'].apply(lambda x: 1 if x == True else 0)
v2_train

C:\Users\advan\AppData\Local\Temp\ipykernel_24148\1096082909.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  v2_train['Customer Validation'] = v2_train['Customer Validation'].apply(lambda x: 0 if x == 'FP' else 1)
C:\Users\advan\AppData\Local\Temp\ipykernel_24148\1096082909.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  v2_train['CoE Validation as per SOP'] = v2_train['CoE Validation as per SOP'].apply(lambda x: 1 if x == True else 0)

,plant_name,plant_id,machine_id,parameter,magnitude,CoE Validation as per SOP,Customer Validation,Increase in magnitude (multiplier),monitor_id,units,org_name,mounting_condition,speed,speed_type,m_category
0,"JSW Steel Coated Products Ltd, Kalmeshwar",1584,8056,TOTAL ACCELERATION,123.60,1,1,139.35,64045,(m/s^2)^2,JSW Steel Ltd,On Rigid Concrete,1482.0,FIXED,blower
1,JSW_ACCIL_Bawal,1823,8682,TEMPERATURE,70.99,1,1,70.99,70384,degree C,JSW Steel Ltd,On Rigid Concrete,2940.0,FIXED,blower
2,"Kansai Nerolac Paints Limited, Bawal",1739,7130,VELOCITY,9.05,1,1,4.76,53308,mm/s,Kansai Nerolac Paints,On Rigid Concrete,2950.0,FIXED,motor
3,Toppan Speciality Films Pvt Ltd_Ropar,95,4190,VELOCITY,3.44,0,1,6.37,305,mm/s,TOPPAN SPECIALITY FILMS PVT LTD,NaN,150.0,VARIABLE,bearing
4,JSW VJNR WRM-2,1726,6782,VELOCITY,3.15,0,1,4.90,50375,mm/s,JSW Steel Ltd,On Rigid Concrete,34.0,FIXED,gearbox
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1184,JSW VJNR Coke Oven - 3,1817,8534,VELOCITY,10.30,1,1,3.16,69648,mm/s,JSW Steel Ltd,At Ground,2985.0,FIXED,motor
1187,JSW Steel Coated Products Ltd_Khopoli Works,1818,9032,TOTAL ACCELERATION,1774.96,1,1,10.52,72494,(m/s^2)^2,JSW Steel Ltd,At Ground,2925.0,FIXED,blower
1190,JSW VJNR RMHS - PCI Silo,1666,6231,VELOCITY,1.53,0,1,3.68,44595,mm/s,JSW Steel Ltd,NaN,60.0,FIXED,bearing
1191,Radha TMT_Smelter_Chegunta_Hyd,1764,7602,TOTAL ACCELERATION,1597.73,1,1,3.97,59520,(m/s^2)^2,Radha Smelters Private Limited,On Rigid Concrete,1490.0,FIXED,blower
1192,Radha TMT_Smelter_Chegunta_Hyd,1764,7602,TOTAL ACCELERATION,2511.90,1,1,6.65,59521,(m/s^2)^2,Radha Smelters Private Limited,On Rigid Concrete,1490.0,FIXED,blower

In [54]:
continuous_columns = ['magnitude','Increase in magnitude (multiplier)','speed']

for col in v2_train.columns:
    if col not in continuous_columns:
        v2_train[col] = pd.factorize(v2_train[col])[0]

C:\Users\advan\AppData\Local\Temp\ipykernel_24148\1014765406.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  v2_train[col] = pd.factorize(v2_train[col])[0]

In [62]:
v2_train
unique_counts = v2_train.nunique()
unique_counts

AttributeError: 'Series' object has no attribute 'toList'

In [56]:
v2_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 637 entries, 0 to 1192
Data columns (total 15 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   plant_name                          637 non-null    int64
 1   plant_id                            637 non-null    int64
 2   machine_id                          637 non-null    int64
 3   parameter                           637 non-null    int64
 4   magnitude                           637 non-null    float64
 5   CoE Validation as per SOP           637 non-null    int64
 6   Customer Validation                 637 non-null    int64
 7   Increase in magnitude (multiplier)  637 non-null    float64
 8   monitor_id                          637 non-null    int64
 9   units                               637 non-null    int64
 10  org_name                            637 non-null    int64
 11  mounting_condition                  637 non-null    int64
 12  speed                               636 non-null    float64
 13  speed_type                          637 non-null    int64
 14  m_category                          637 non-null    int64
dtypes: float64(3), int64(12)
memory usage: 79.6 KB

In [60]:
v2_train

,plant_name,plant_id,machine_id,parameter,magnitude,CoE Validation as per SOP,Customer Validation,Increase in magnitude (multiplier),monitor_id,units,org_name,mounting_condition,speed,speed_type,m_category
0,0,0,0,0,123.60,0,0,139.35,0,0,0,0,1482.0,0,0
1,1,1,1,1,70.99,0,0,70.99,1,1,0,0,2940.0,0,0
2,2,2,2,2,9.05,0,0,4.76,2,2,1,0,2950.0,0,1
3,3,3,3,2,3.44,1,0,6.37,3,2,2,1,150.0,1,2
4,4,4,4,2,3.15,1,0,4.90,4,2,0,0,34.0,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1184,78,78,275,2,10.30,0,0,3.16,390,2,0,3,2985.0,0,1
1187,24,24,276,0,1774.96,0,0,10.52,391,0,0,3,2925.0,0,0
1190,36,36,178,2,1.53,1,0,3.68,392,2,0,1,60.0,0,2
1191,10,10,39,0,1597.73,0,0,3.97,181,0,7,0,1490.0,0,0
1192,10,10,39,0,2511.90,0,0,6.65,61,0,7,0,1490.0,0,0

In [61]:
file_path = 'C:\\Users\\advan\\OneDrive\\Desktop\\Infinite Uptime\\DATA\\v2_train.xlsx'

# Save the DataFrame to Excel
v2_train.to_excel(file_path, index=False)

In [63]:
min_values = v2_train[continuous_columns].min()
max_values = v2_train[continuous_columns].max()
print(min_values)
print(max_values)

magnitude                             1.21
Increase in magnitude (multiplier)    3.00
speed                                 0.00
dtype: float64
magnitude                              7012.51
Increase in magnitude (multiplier)    12087.58
speed                                 12500.00
dtype: float64